### ISSUE TITLE
Diagonal movement can cause animations to work incorrectly

### ISSUE THREAD

**Issue by kurtwheeler** [ayaigame/ayai-frontend#12]
Hey those animations look really good! While I was playing with them I noticed that if you move diagonally then unpress one of the keys so you're going up, down, left, or right then the animation stops and you just slide in that direction.

BTW I think that you were doing this Rob but if not then just reassign this bug to whoever did put that in.

**Comment by rtmruczek** [comment]
Oh yeah I didn't get around to fixing this yet. I'll try to fit it in my updates for tomorrow.
